#!/usr/bin/env bash
# RSA Factorization Challenge

check_factor()
{
if [ $# -ne 3 ];
then
args=("$@")
counter=0
num2=1
for b in ${args[*]};
do
if [ $counter -gt 1 ];
then
num2=$(echo $b*$num2 | bc)
fi
counter=$((counter + 1))
done
else
num2=$3
fi
num1=$2
num=$(echo "$1" | tr ':' '=')
res=$(echo "if($num2 > $num1) 1 else 0" | bc)
if ((res == 1)); then
numcp=$num1
num1=$num2
num2=$numcp
fi
echo "$num$num1*$num2"
}

if [ $# -ne 1 ]
then
echo 'Usage: rsa <file>'
exit 1
else
while read j
do
res=$(factor "$j")
check_factor $res
done < "$1"
fi
